// fifo1.v

// Generated using ACDS version 18.1 222

`timescale 1 ps / 1 ps
module fifo1 (
		input  wire [73:0] data,  //  fifo_input.datain
		input  wire        wrreq, //            .wrreq
		input  wire        rdreq, //            .rdreq
		input  wire        clock, //            .clk
		output wire [73:0] q,     // fifo_output.dataout
		output wire [6:0]  usedw  //            .usedw
	);

	fifo1_fifo_181_ohbjxzi fifo_0 (
		.data  (data),  //   input,  width = 74,  fifo_input.datain
		.wrreq (wrreq), //   input,   width = 1,            .wrreq
		.rdreq (rdreq), //   input,   width = 1,            .rdreq
		.clock (clock), //   input,   width = 1,            .clk
		.q     (q),     //  output,  width = 74, fifo_output.dataout
		.usedw (usedw)  //  output,   width = 7,            .usedw
	);

endmodule
